name: Simple Deploy to AWS

on:
  push:
    branches: [demo1, main, production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > deploy_key
          chmod 600 deploy_key
          ssh -o StrictHostKeyChecking=no -i deploy_key ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd ~/CredLink
            git pull origin main
            npx prisma generate
            npm run build
            pm2 restart all
          EOF
          rm deploy_key
